/**
 * Created by youmc on 2017/1/16.
 */

// function keyMirror (obj) {
//   if (obj instanceof Object) {
//     var _obj = Object.assign({}, obj)
//     var _keyArray = Object.keys(obj)
//     _keyArray.forEach(key => { _obj[key] = key })
//     return _obj
//   }
// }
//
// export const types = keyMirror({
//   PAGE_SET_OTHER_FLAG: null
// })

export const PAGE_SET_OTHER_FLAG = 'PAGE_SET_OTHER_FLAG'

export const CUSTOMER_DATA_LOAD_MORE = 'CUSTOMER_DATA_LOAD_MORE'
export const CUSTOMER_DATA_REFRESH = 'CUSTOMER_DATA_REFRESH'
export const CUSTOMER_SET = 'CUSTOMER_SET'
export const CUSTOMER_DATA_SERVICE = 'CUSTOMER_DATA_SERVICE'
export const CUSTOMER_DATA_FLIGHT = 'CUSTOMER_DATA_FLIGHT'
export const CUSTOMER_CHECKED_SET = 'CUSTOMER_CHECKED_SET'

export const PORT_DATA_LOAD_MORE = 'PORT_DATA_LOAD_MORE'
export const PORT_DATA_REFRESH = 'PORT_DATA_REFRESH'
export const PORT_ID_SET = 'PORT_ID_SET'

export const MESSAGE_DATA_REFRESH = 'MESSAGE_DATA_REFRESH'
export const MESSAGE_DATA_UPDATE = 'MESSAGE_DATA_UPDATE'
export const MESSAGE_DATA_SAVE = 'MESSAGE_DATA_SAVE'
export const MESSAGE_DATA_REMOVE = 'MESSAGE_DATA_REMOVE'
export const MESSAGE_SET = 'MESSAGE_SET'

export const CONTACTRECORDS_DATA_REFRESH = 'CONTACTRECORDS_DATA_REFRESH'
export const CONTACTRECORDS_DATA_GET_NOANSWER = 'CONTACTRECORDS_DATA_GET_NOANSWER'

export const TASK_DATA_LOAD_MORE = 'TASK_DATA_LOAD_MORE'
export const TASK_DATA_REFRESH = 'TASK_DATA_REFRESH'
export const TASK_DATA_PREVIOUS = 'TASK_DATA_PREVIOUS'
export const TASK_DATA_SAVE = 'TASK_DATA_SAVE'
export const TASK_DATA_UPDATE = 'TASK_DATA_UPDATE'

export const MEMO_DATA_REFRESH = 'MEMO_DATA_REFRESH'
export const MEMO_DATA_SAVE = 'MEMO_DATA_SAVE'
export const MEMO_DATA_REMOVE = 'MEMO_DATA_REMOVE'
export const MEMO_DATA_UPDATE = 'MEMO_DATA_UPDATE'
export const MEMO_SET = 'MEMO_SET'

export const REMARK_DATA_REFRESH = 'REMARK_DATA_REFRESH'
export const REMARK_DATA_SAVE = 'REMARK_DATA_SAVE'
export const REMARK_DATA_REMOVE = 'REMARK_DATA_REMOVE'
export const REMARK_DATA_UPDATE = 'REMARK_DATA_UPDATE'
export const REMARK_SET = 'REMARK_SET'

export const CUSTOMERMGT_CHECKED_SET = 'CUSTOMERMGT_CHECKED_SET'
export const CUSTOMER_DATA_MANAGER = 'CUSTOMER_DATA_MANAGER'
export const CUSTOMER_DATA_TRUSTEESHIP = 'CUSTOMER_DATA_TRUSTEESHIP'
export const CUSTOMERTRUST_CHECKED_SET = 'CUSTOMERTRUST_CHECKED_SET'
export const CUSTOMER_DATA_ALLOCATIONNEXT = 'CUSTOMER_DATA_ALLOCATIONNEXT'
export const CUSTOMERALLOCATIONNEXT_CHECKED_SET = 'CUSTOMERALLOCATIONNEXT_CHECKED_SET'
export const CUSTOMER_DATA_ALLOCATIONFILTER = 'CUSTOMER_DATA_ALLOCATIONFILTER'
export const CUSTOMERALLOCATIONFILTER_CHECKED_SET = 'CUSTOMERALLOCATIONFILTER_CHECKED_SET'
export const CUSTOMERALLOCATIONNEXT_CHECKED_SELECTALL = 'CUSTOMERALLOCATIONNEXT_CHECKED_SELECTALL'
export const CUSTOMER_DATA_TRUSTEESHIPCANCEL = 'CUSTOMER_DATA_TRUSTEESHIPCANCEL'
export const CUSTOMERMGT_DATA_SAVE = 'CUSTOMERMGT_DATA_SAVE'
export const CONTACTINTERNAL_DATA_LOAD_MORE = 'CONTACTINTERNAL_DATA_LOAD_MORE'
export const CONTACTINTERNAL_DATA_REFRESH = 'CONTACTINTERNAL_DATA_REFRESH'
export const JUMPTO = 'JUMPTO'
export const REFRESHREPAIRDETAIL = 'REFRESHREPAIRDETAIL'
export const REFRESHREPAIR = 'REFRESHREPAIR'
export const LOAD_MORE_REPAIR = 'LOAD_MORE_REPAIR'
export const REFRESHREPAIR_PERSON = 'REFRESHREPAIR_PERSON'

export const REPAIRDETAIL_ADD_SET = 'REPAIRDETAIL_ADD_SET'
export const COLOR_HUI = 'COLOR_HUI'
export const REPAIRDETAIL_COLOR_SET = 'REPAIRDETAIL_COLOR_SET'
export const REPAIRDETAIL_DEL_SET = 'REPAIRDETAIL_DEL_SET'
export const PERMISSION = 'PERMISSION'
export const LOADMORE_PERSON = 'LOADMORE_PERSON'

export const REFRESH_DEVELOPED = 'REFRESH_DEVELOPED'
export const DEVELOPED_LOAD_MORE= 'DEVELOPED_LOAD_MORE'

export const JOINMEMBER= 'JOINMEMBER'

